const COUNTRIES = [
    {
        country: "Argentina",
        complexity: 4.37,
        color: 5.62,
        hierarchy: 49,
    },
    {
        country: "Australia",
        complexity: 4.09,
        color: 5.53,
        hierarchy: 38,
    },
    {
        country: "Austria",
        complexity: 3.93,
        color: 4.55,
        hierarchy: 11,
    },
    {
        country: "Belgium",
        complexity: 3.85,
        color: 5.28,
        hierarchy: 65,
    },
    {
        country: "Brazil",
        complexity: 4,
        color: 5.15,
        hierarchy: 69,
    },
    {
        country: "Bulgaria",
        complexity: 4.26,
        color: 4.63,
        hierarchy: 70,
    },
    {
        country: "Canada",
        complexity: 4.2,
        color: 5.89,
        hierarchy: 39,
    },
    {
        country: "Chile",
        complexity: 4.65,
        color: 6.95,
        hierarchy: 63,
    },
    {
        country: "China",
        complexity: 4.09,
        color: 6.27,
        hierarchy: 80,
    },
    {
        country: "Denmark",
        complexity: 3.69,
        color: 4.24,
        hierarchy: 18,
    },
    {
        country: "Finland",
        complexity: 3.31,
        color: 3.56,
        hierarchy: 33,
    },
    {
        country: "France",
        complexity: 3.78,
        color: 4.41,
        hierarchy: 68,
    },
    {
        country: "Germany",
        complexity: 3.75,
        color: 4.45,
        hierarchy: 35,
    },
    {
        country: "Greece",
        complexity: 4.09,
        color: 6.21,
        hierarchy: 60,
    },
    {
        country: "Hong Kong",
        complexity: 4.09,
        color: 6.21,
        hierarchy: 68,
    },
    {
        country: "Hungary",
        complexity: 4.54,
        color: 5.93,
        hierarchy: 46,
    },
    {
        country: "India",
        complexity: 4.08,
        color: 5.73,
        hierarchy: 77,
    },
    {
        country: "Ireland",
        complexity: 4.29,
        color: 6.37,
        hierarchy: 28,
    },
    {
        country: "Israel",
        complexity: 3.9,
        color: 5.08,
        hierarchy: 13,
    },
    {
        country: "Italy",
        complexity: 3.74,
        color: 5.63,
        hierarchy: 50,
    },
    {
        country: "Japan",
        complexity: 4.08,
        color: 5.36,
        hierarchy: 54,
    },
    {
        country: "Lithuania",
        complexity: 4.28,
        color: 6.15,
        hierarchy: 42,
    },
    {
        country: "Macedonia",
        complexity: 4.46,
        color: 7.62,
        hierarchy: 90,
    },
    {
        country: "Malaysia",
        complexity: 4.39,
        color: 6.97,
        hierarchy: 100,
    },
    {
        country: "Mexico",
        complexity: 4.56,
        color: 6.36,
        hierarchy: 81,
    },
    {
        country: "Netherlands",
        complexity: 3.88,
        color: 5.35,
        hierarchy: 38,
    },
    {
        country: "New Zealand",
        complexity: 4.22,
        color: 5.73,
        hierarchy: 22,
    },
    {
        country: "Norway",
        complexity: 3.86,
        color: 4.77,
        hierarchy: 31,
    },
    {
        country: "Philippines",
        complexity: 4.28,
        color: 5.9,
        hierarchy: 94,
    },
    {
        country: "Poland",
        complexity: 3.75,
        color: 3.83,
        hierarchy: 68,
    },
    {
        country: "Portugal",
        complexity: 3.99,
        color: 4.95,
        hierarchy: 63,
    },
    {
        country: "Romania",
        complexity: 4.5,
        color: 6.3,
        hierarchy: 90,
    },
    {
        country: "Russia",
        complexity: 2.51,
        color: 3.62,
        hierarchy: 93,
    },
    {
        country: "Serbia",
        complexity: 4.77,
        color: 6.6,
        hierarchy: 86,
    },
    {
        country: "Singapore",
        complexity: 4.53,
        color: 6.39,
        hierarchy: 74,
    },
    {
        country: "Slovakia",
        complexity: 3.94,
        color: 5.11,
        hierarchy: 100,
    },
    {
        country: "South Africa",
        complexity: 4.54,
        color: 5.94,
        hierarchy: 49,
    },
    {
        country: "Spain",
        complexity: 4.36,
        color: 5.76,
        hierarchy: 57,
    },
    {
        country: "Sweden",
        complexity: 3.39,
        color: 4.5,
        hierarchy: 31,
    },
    {
        country: "Switzerland",
        complexity: 3.7,
        color: 4.25,
        hierarchy: 34,
    },
    {
        country: "United Kingdom",
        complexity: 4.52,
        color: 6.52,
        hierarchy: 35,
    },
    {
        country: "United States",
        complexity: 4.15,
        color: 6.09,
        hierarchy: 40,
    },
];

export default COUNTRIES;
